spring.application.name=jixly

spring.datasource.url=jdbc:postgresql://localhost:5432/jixly
spring.datasource.username=postgres
spring.datasource.password=ffcup9090

spring.jpa.hibernate.ddl-auto=update
